CONFIGS = {
    "cifar100_resnet32_sdn": {
        "ic_layers": [
            "layer1.2",
            "layer1.4",
            "layer2.1",
            "layer2.3",
            "layer3.0",
            "layer3.2",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_fc",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": [0.15, 0.3, 0.45, 0.6, 0.75, 0.9],
        "detach_ics": False,
    },
    "cifar100_resnet32_sdn_cascading": {
        "ic_layers": [
            "layer1.2",
            "layer1.4",
            "layer2.1",
            "layer2.3",
            "layer3.0",
            "layer3.2",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_cascading_conv",
            "standard_cascading_conv",
            "standard_cascading_conv",
            "standard_cascading_conv",
            "standard_cascading_conv",
            "cascading_fc",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": [0.15, 0.3, 0.45, 0.6, 0.75, 0.9],
        "detach_ics": False,
    },
    "cifar100_resnet32_sdn_ensembling": {
        "ic_layers": [
            "layer1.2",
            "layer1.4",
            "layer2.1",
            "layer2.3",
            "layer3.0",
            "layer3.2",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_ensembling_conv",
            "standard_ensembling_conv",
            "standard_ensembling_conv",
            "standard_ensembling_conv",
            "standard_ensembling_conv",
            "ensembling_fc",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": [0.15, 0.3, 0.45, 0.6, 0.75, 0.9],
        "detach_ics": False,
    },
    "cifar100_resnet32_sdn_detach": {
        "ic_layers": [
            "layer1.2",
            "layer1.4",
            "layer2.1",
            "layer2.3",
            "layer3.0",
            "layer3.2",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": [0.15, 0.3, 0.45, 0.6, 0.75, 0.9],
        "detach_ics": True,
    },
    "cifar100_resnet32_sparse": {
        "ic_layers": [
            "layer1.2",
            "layer2.1",
            "layer3.0",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
        ],
        "ic_type": ["standard_conv", "standard_conv", "standard_conv", "standard_fc"],
        "input_size": [3, 32, 32],
        "ic_weighting": [0.15, 0.45, 0.75],
        "detach_ics": False,
    },
    "cifar100_resnet32_dense": {
        "ic_layers": [
            "layer1.2",
            "layer1.3",
            "layer1.4",
            "layer2.0",
            "layer2.1",
            "layer2.2",
            "layer2.3",
            "layer2.4",
            "layer3.0",
            "layer3.1",
            "layer3.2",
            "layer3.3",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_fc",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": [
            0.15,
            0.225,
            0.3,
            0.375,
            0.45,
            0.525,
            0.6,
            0.675,
            0.75,
            0.825,
            0.9,
            0.95,
        ],
        "detach_ics": False,
    },
    "imagenet100_resnet18_sdn": {
        "ic_layers": [
            "layer1.1",
            "layer2.0",
            "layer2.1",
            "layer3.0",
            "layer3.1",
            "layer4.0",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "adaptive_standard_conv",
            "standard_fc",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": [0.3, 0.4, 0.55, 0.65, 0.8, 0.9],
        "detach_ics": False,
    },
    "imagenet100_resnet18_dense": {
        "ic_layers": [
            "layer1.0",
            "layer1.1",
            "layer2.0",
            "layer2.1",
            "layer3.0",
            "layer3.1",
            "layer4.0",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "adaptive_standard_conv",
            "adaptive_standard_conv",
            "standard_fc",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": [0.2, 0.3, 0.4, 0.55, 0.65, 0.8, 0.9],
        "detach_ics": False,
    },
    "imagenet100_vit_base": {
        "ic_layers": [
            "encoder.layers.encoder_layer_0",
            "encoder.layers.encoder_layer_1",
            "encoder.layers.encoder_layer_2",
            "encoder.layers.encoder_layer_3",
            "encoder.layers.encoder_layer_4",
            "encoder.layers.encoder_layer_5",
            "encoder.layers.encoder_layer_6",
            "encoder.layers.encoder_layer_7",
            "encoder.layers.encoder_layer_8",
            "encoder.layers.encoder_layer_9",
            "encoder.layers.encoder_layer_10",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_fc",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": [
            0.08,
            0.16,
            0.24,
            0.32,
            0.4,
            0.48,
            0.56,
            0.64,
            0.72,
            0.8,
            0.88,
        ],
        "detach_ics": False,
    },
    "imagenet100_vit_base_dense": {
        "ic_layers": [
            "encoder.layers.encoder_layer_0.ln_2",
            "encoder.layers.encoder_layer_0",
            "encoder.layers.encoder_layer_1.ln_2",
            "encoder.layers.encoder_layer_1",
            "encoder.layers.encoder_layer_2.ln_2",
            "encoder.layers.encoder_layer_2",
            "encoder.layers.encoder_layer_3.ln_2",
            "encoder.layers.encoder_layer_3",
            "encoder.layers.encoder_layer_4.ln_2",
            "encoder.layers.encoder_layer_4",
            "encoder.layers.encoder_layer_5.ln_2",
            "encoder.layers.encoder_layer_5",
            "encoder.layers.encoder_layer_6.ln_2",
            "encoder.layers.encoder_layer_6",
            "encoder.layers.encoder_layer_7.ln_2",
            "encoder.layers.encoder_layer_7",
            "encoder.layers.encoder_layer_8.ln_2",
            "encoder.layers.encoder_layer_8",
            "encoder.layers.encoder_layer_9.ln_2",
            "encoder.layers.encoder_layer_9",
            "encoder.layers.encoder_layer_10.ln_2",
            "encoder.layers.encoder_layer_10",
            "encoder.layers.encoder_layer_11.ln_2",
        ],
        "hook_placements": [
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
        ],
        "ic_type": [
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_fc",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": [
            0.04,
            0.08,
            0.12,
            0.16,
            0.20,
            0.24,
            0.28,
            0.32,
            0.36,
            0.4,
            0.44,
            0.48,
            0.52,
            0.56,
            0.6,
            0.64,
            0.68,
            0.72,
            0.76,
            0.8,
            0.84,
            0.88,
            0.92,
        ],
        "detach_ics": False,
    },
    "imagenet100_vit_ln": {
        "ic_layers": [
            "encoder.layers.encoder_layer_0",
            "encoder.layers.encoder_layer_1",
            "encoder.layers.encoder_layer_2",
            "encoder.layers.encoder_layer_3",
            "encoder.layers.encoder_layer_4",
            "encoder.layers.encoder_layer_5",
            "encoder.layers.encoder_layer_6",
            "encoder.layers.encoder_layer_7",
            "encoder.layers.encoder_layer_8",
            "encoder.layers.encoder_layer_9",
            "encoder.layers.encoder_layer_10",
        ],
        "hook_placements": [
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
            "output",
        ],
        "ic_type": [
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "standard_fc",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": [
            0.08,
            0.16,
            0.24,
            0.32,
            0.4,
            0.48,
            0.56,
            0.64,
            0.72,
            0.8,
            0.88,
        ],
        "detach_ics": False,
    },
    "imagenet100_vit_ln_dense": {
        "ic_layers": [
            "encoder.layers.encoder_layer_0.ln_2",
            "encoder.layers.encoder_layer_0",
            "encoder.layers.encoder_layer_1.ln_2",
            "encoder.layers.encoder_layer_1",
            "encoder.layers.encoder_layer_2.ln_2",
            "encoder.layers.encoder_layer_2",
            "encoder.layers.encoder_layer_3.ln_2",
            "encoder.layers.encoder_layer_3",
            "encoder.layers.encoder_layer_4.ln_2",
            "encoder.layers.encoder_layer_4",
            "encoder.layers.encoder_layer_5.ln_2",
            "encoder.layers.encoder_layer_5",
            "encoder.layers.encoder_layer_6.ln_2",
            "encoder.layers.encoder_layer_6",
            "encoder.layers.encoder_layer_7.ln_2",
            "encoder.layers.encoder_layer_7",
            "encoder.layers.encoder_layer_8.ln_2",
            "encoder.layers.encoder_layer_8",
            "encoder.layers.encoder_layer_9.ln_2",
            "encoder.layers.encoder_layer_9",
            "encoder.layers.encoder_layer_10.ln_2",
            "encoder.layers.encoder_layer_10",
            "encoder.layers.encoder_layer_11.ln_2",
        ],
        "hook_placements": [
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
            "output",
            "input",
        ],
        "ic_type": [
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "standard_fc",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": [
            0.04,
            0.08,
            0.12,
            0.16,
            0.2,
            0.24,
            0.28,
            0.32,
            0.36,
            0.4,
            0.44,
            0.48,
            0.52,
            0.56,
            0.6,
            0.64,
            0.68,
            0.72,
            0.76,
            0.8,
            0.84,
            0.88,
            0.92,
            0.96,
        ],
        "detach_ics": False,
    },
    "test_mnist": {
        "ic_type": ["standard_conv", "standard_conv", "standard_fc", "standard_fc"],
        "hook_placements": ["output", "output", "output"],
        "ic_layers": ["conv1", "conv2", "fc1"],
        "input_size": [1, 28, 28],
        "ic_weighting": [0.3, 0.6, 0.8],
        "detach_ics": False,
    },
    "test_mnist_cascading": {
        "ic_type": [
            "standard_conv",
            "standard_cascading_conv",
            "cascading_fc",
            "cascading_fc",
        ],
        "hook_placements": ["output", "output", "output"],
        "ic_layers": ["conv1", "conv2", "fc1"],
        "input_size": [1, 28, 28],
        "ic_weighting": [0.3, 0.6, 0.8],
        "detach_ics": False,
    },
}
