CONFIGS = {
    "cifar100_resnet32_sdn": {
        "ic_layers": [
            "layer1.2",
            "layer1.4",
            "layer2.1",
            "layer2.3",
            "layer3.0",
            "layer3.2",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": "sdn",
        "detach_ics": False,
    },
    "cifar100_resnet32_prop": {
        "ic_layers": [
            "layer1.2",
            "layer1.4",
            "layer2.1",
            "layer2.3",
            "layer3.0",
            "layer3.2",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "cifar100_resnet32_dense": {
        "ic_layers": [
            "layer1.0",
            "layer1.1",
            "layer1.2",
            "layer1.3",
            "layer1.4",
            "layer2.0",
            "layer2.1",
            "layer2.2",
            "layer2.3",
            "layer2.4",
            "layer3.0",
            "layer3.1",
            "layer3.2",
            "layer3.3",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "cifar100_resnet32_dense_2x": {
        "ic_layers": [
            "layer1.0.relu",
            "layer1.0",
            "layer1.1.relu",
            "layer1.1",
            "layer1.2.relu",
            "layer1.2",
            "layer1.3.relu",
            "layer1.3",
            "layer1.4.relu",
            "layer1.4",
            "layer2.0.relu",
            "layer2.0",
            "layer2.1.relu",
            "layer2.1",
            "layer2.2.relu",
            "layer2.2",
            "layer2.3.relu",
            "layer2.3",
            "layer2.4.relu",
            "layer2.4",
            "layer3.0.relu",
            "layer3.0",
            "layer3.1.relu",
            "layer3.1",
            "layer3.2.relu",
            "layer3.2",
            "layer3.3.relu",
            "layer3.3",
            "layer3.4.relu",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
        ],
        "input_size": [3, 32, 32],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "imagenet100_resnet18_sdn": {
        "ic_layers": [
            "layer1.1",
            "layer2.0",
            "layer2.1",
            "layer3.0",
            "layer3.1",
            "layer4.0",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "adaptive_standard_conv",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": "sdn",
        "detach_ics": False,
    },
    "imagenet100_resnet18_prop": {
        "ic_layers": [
            "layer1.1",
            "layer2.0",
            "layer2.1",
            "layer3.0",
            "layer3.1",
            "layer4.0",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "adaptive_standard_conv",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "imagenet100_resnet18_dense": {
        "ic_layers": [
            "layer1.0.relu",
            "layer1.0",
            "layer1.1.relu",
            "layer1.1",
            "layer2.0.relu",
            "layer2.0",
            "layer2.1.relu",
            "layer2.1",
            "layer3.0.relu",
            "layer3.0",
            "layer3.1.relu",
            "layer3.1",
            "layer4.0.relu",
            "layer4.0",
            "layer4.1.relu",
        ],
        "ic_type": [
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "standard_conv",
            "adaptive_standard_conv",
            "adaptive_standard_conv",
            "adaptive_standard_conv",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "imagenet100_vit_base": {
        "ic_layers": [
            "encoder.layers.encoder_layer_0",
            "encoder.layers.encoder_layer_1",
            "encoder.layers.encoder_layer_2",
            "encoder.layers.encoder_layer_3",
            "encoder.layers.encoder_layer_4",
            "encoder.layers.encoder_layer_5",
            "encoder.layers.encoder_layer_6",
            "encoder.layers.encoder_layer_7",
            "encoder.layers.encoder_layer_8",
            "encoder.layers.encoder_layer_9",
            "encoder.layers.encoder_layer_10",
        ],
        "ic_type": [
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
            "standard_transformer",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "imagenet100_vit_ln": {
        "ic_layers": [
            "encoder.layers.encoder_layer_0",
            "encoder.layers.encoder_layer_1",
            "encoder.layers.encoder_layer_2",
            "encoder.layers.encoder_layer_3",
            "encoder.layers.encoder_layer_4",
            "encoder.layers.encoder_layer_5",
            "encoder.layers.encoder_layer_6",
            "encoder.layers.encoder_layer_7",
            "encoder.layers.encoder_layer_8",
            "encoder.layers.encoder_layer_9",
            "encoder.layers.encoder_layer_10",
        ],
        "ic_type": [
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
            "ln_transformer",
        ],
        "input_size": [3, 224, 224],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
    "test_mnist": {
        "ic_type": ["standard_conv", "standard_conv", "standard_fc"],
        "ic_layers": ["conv1", "conv2", "fc1"],
        "input_size": [1, 28, 28],
        "ic_weighting": "proportional",
        "detach_ics": False,
    },
}
